const gamevarLines = [
  "var_name,comment,var_type,var_value,var_region,var_platform",

  // === SENSITIVITY ===
  "SensitivityMaxSetting,SensitivityMaxSetting,float,9.5,,",
  "Sensitivity1PMaxSetting,Sensitivity1PMaxSetting,float,9.5,,",
  "X1ScopeMaxSetting,X1ScopeMaxSetting,float,9.5,,",
  "X2ScopeMaxSetting,X2ScopeMaxSetting,float,9.5,,",
  "X4ScopeMaxSetting,X4ScopeMaxSetting,float,9.5,,",
  "X8ScopeMaxSetting,X8ScopeMaxSetting,float,9.5,,",
  "FreeLookMaxSetting,FreeLookMaxSetting,float,9.5,,",
  "FreeMoveAngularSpeed,FreeMoveAngularSpeed,float,6.9,,",
  "FreeMoveAngularSpeedStand,FreeMoveAngularSpeedStand,float,10.0,,",
  "FreeMoveAngularSpeedCrouch,FreeMoveAngularSpeedCrouch,float,6.9,,",
  "FreeMoveAngularSpeedCreep,FreeMoveAngularSpeedCreep,float,6.9,,",
  "ResetRotationSpeed,ResetRotationSpeed,float,10.0,,",

  // === ANIMATION ===
  "NoResetUplayerAnimationWhenReloading,NoResetUplayerAnimationWhenReloading,bool,True,,",
  "KeepFallingLandAnim,KeepFallingLandAnim,bool,False,,",
  "CallStopEmoteAtPlayFireAnim,CallStopEmoteAtPlayFireAnim,bool,True,,",
  "BanFastRunWhenFire,BanFastRunWhenFire,bool,True,,",
  "FixCrouchFireAnim,FixCrouchFireAnim,bool,True,,",

  // === HACK DETECTION (DISABLED) ===
  "EnableIceWallHacker,EnableIceWallHacker,bool,True,,",
  "EnableIceWallHackerKill,EnableIceWallHackerKill,bool,True,,",
  "EnableHipHackerKill,EnableHipHackerKill,bool,True,,",
  "EnableSendHackStoreLog,EnableSendHackStoreLog,bool,False,,",
  "CameraHackRuntimeCheckIsWaitingCabinPhase,CameraHackRuntimeCheckIsWaitingCabinPhase,bool,False,,",
  "DisableErrorLog,DisableErrorLog,bool,True,,",
  "EnableCheckSandModeBySwitchFunc,EnableCheckSandModeBySwitchFunc,bool,False,,",

  // === ANTI CHEAT ===
  "CleanFFAntiState,CleanFFAntiState,bool,True,,",
  "SaveLocationInPlatform,SaveLocationInPlatform,bool,False,,",
  "EnableGGPDecryptFailureProtection,EnableGGPDecryptFailureProtection,bool,False,,",
  "EnableFileInfoEncryptionAndroid,EnableFileInfoEncryptionAndroid,bool,False,,",
  "EnableFileInfoEncryptionIOS,EnableFileInfoEncryptionIOS,bool,False,,",
  "OptionalDeepFileCheck,OptionalDeepFileCheck,bool,False,,",
  "EnableOBBCheck,EnableOBBCheck,bool,False,,",
  "ModifyAvatarCode,ModifyAvatarCode,bool,False,,",
  "ModifyAvatarDataCode,ModifyAvatarDataCode,bool,False,,",
  "NeedSignatureInfo,NeedSignatureInfo,bool,True,,",
  "EnableFirebase_Crashlytics,EnableFirebase_Crashlytics,bool,False,,",
  "FFAntihackDisabledRegions,FFAntihackDisabledRegions,string,ID,,",
  "FFAntihackDisabledClientVariant,FFAntihackDisabledClientVariant,string,ClientUsingVersion_NONE,,",
  "EnableMtpLiteDataRegion,EnableMtpLiteDataRegion,string,BR;EUROPE;ID;ME;US;RU;SAC;SG;TH;TW;VN;PK;ZA;BD,,",
  "FFAntihackEmulatorCheckDisbaledClientVariant,FFAntihackEmulatorCheckDisbaledClientVariant,string,ClientUsingVersion_NONE,,",
  "ForceTutorial_ChangeHudABTest,ForceTutorial_ChangeHudABTest,float,-1,,",
  "EnableFFAntihackInfoExtra,EnableFFAntihackInfoExtra,bool,False,,",
  "EnableTrustItemCountFromServer,EnableTrustItemCountFromServer,bool,False,,",
  "EnableNativeCheck,EnableNativeCheck,bool,False,,",
  "EnablePlatformCheck,EnablePlatformCheck,bool,False,,",
  "EnableMMKPlatformCheck,EnableMMKPlatformCheck,bool,False,,",
  "EnableSupCheck,EnableSupCheck,bool,False,,",
  "EnableCheckFileStates,EnableCheckFileStates,bool,False,,",
  "OptionalDownloadHashCheckOpen,OptionalDownloadHashCheckOpen,bool,False,,",
  "MemoryCheckString,MemoryCheckString,string,,,",
  "AgeCtrlAndroidBanCheckByInstallID,AgeCtrlAndroidBanCheckByInstallID,bool,False,,",
  "ReturnToLobbyCheckAlbumOverTimeFile,ReturnToLobbyCheckAlbumOverTimeFile,bool,False,,",
  "EnableCheckOverlapWithSantioDummy,EnableCheckOverlapWithSantioDummy,bool,False,,",
  "EnableIngameQuickReport,EnableIngameQuickReport,bool,False,,",
  "AgeCtrl_iOSPrecheckForMinor,AgeCtrl_iOSPrecheckForMinor,bool,False,,",
  "AgeCtrl_CheckForThirdPartyBuild,AgeCtrl_CheckForThirdPartyBuild,bool,False,,",
  "AgeCtrl_PromptWhenBannedByStrategy_iOS,AgeCtrl_PromptWhenBannedByStrategy_iOS,bool,False,,",
  "AgeCtrl_PromptWhenBannedByStrategy_Android,AgeCtrl_PromptWhenBannedByStrategy_Android,bool,False,,",
  "BanStateDisabledArea,BanStateDisabledArea,string,US,,",
  "EnableCheckMatchEndDelayWhenDisconnect,EnableCheckMatchEndDelayWhenDisconnect,bool,False,,",
  "ChatReportMaxTimes,ChatReportMaxTimes,uint32,0,,",
  "ClanReportMaxTimes,ClanReportMaxTimes,uint32,0,,",
  "BlocklistMaxNum,BlocklistMaxNum,Int32,0,,",
  "ANODisabledRegions,ANODisabledRegions,string,ID,,",
  "ANODisabledClientVariant,ANODisabledClientVariant,string,ClientUsingVersion_FFI;ClientUsingVersion_MAX;ClientUsingVersion_NORMAL,,",
  "ANOEmulatorCheckDisbaledClientVariant,ANOEmulatorCheckDisbaledClientVariant,string,ClientUsingVersion_FFI;ClientUsingVersion_MAX;ClientUsingVersion_NORMAL,,",
  "FFAntihackDefenceLevel,FFAntihackDefenceLevel,string,0,,",
  "FFAntihackLightInitOnThread,FFAntihackLightInitOnThread,bool,false,,",
  "FFAntihackSDKDetailEncryptBySHA1,FFAntihackSDKDetailEncryptBySHA1,bool,false,,",
  "CheckHacker,CheckHacker,bool,false,,",
  "DebugHack,DebugHack,bool,true,,",
  "TestModeEnabled,TestModeEnabled,bool,true,,",
  "EarlyInitGGP,EarlyInitGGP,bool,false,,",
  "DisableGinInfoSend,DisableGinInfoSend,int,1,,",
  "GinInfoBRAliveThreshold,GinInfoBRAliveThreshold,int,0,,",
  "AntiHackResetSubgameInterval,AntiHackResetSubgameInterval,int,0,,",
  "FFANTIHACKEXT_SPLIT_THRESHOLD,FFANTIHACKEXT_SPLIT_THRESHOLD,int,0,,",
  "NeedProcessAH,NeedProcessAH,bool,true,,",

  // === ALBUM / SCREENSHOT ===
  "IsAlbumScreenShotNeedAntiMod,IsAlbumScreenShotNeedAntiMod,bool,false,,",
  "SystemAlbumImageAntiModStrategy,SystemAlbumImageAntiModStrategy,int,0,,",
  "AlbumImageAntiModSecs,AlbumImageAntiModSecs,int,0,,",
  "AlbumImageAntiMod_iOS,AlbumImageAntiMod_iOS,bool,false,,",

  // === PERFORMANCE ===
  "ShowHighFrameRateSetting,ShowHighFrameRateSetting,bool,true,,",
  "Real60FrameSwitch,Real60FrameSwitch,bool,true,,",
  "HighFPSSetting,HighFPSSetting,bool,true,,",

  // === GGP ===
  "GGPLoginOnce,GGPLoginOnce,bool,true,,",
  "EnableGGPOnLowMemory,EnableGGPOnLowMemory,bool,true,,",
  "GGPUpdateFlag,GGPUpdateFlag,int,99999,,",

  // === BUG REPORT ===
  "EnableBugReportTime,EnableBugReportTime,bool,false,,",
  "EnableBugReportEarly,EnableBugReportEarly,int,0,,",
  "BugReportMaxCountPerSession,BugReportMaxCountPerSession,int,0,,",
  "BugReportIntervalOnLowMemory,BugReportIntervalOnLowMemory,int,0,,",
  "ReportInstantiateJank,ReportInstantiateJank,bool,false,,",
  "InstantiateJankTimeLimit,InstantiateJankTimeLimit,int,0,,",

  // === REPORT COUNTS ===
  "Reportee_Damager_RecentlyMaxCnt,Reportee_Damager_RecentlyMaxCnt,int,99999,,",
  "Reportee_Killer_RecentlyMaxCnt,Reportee_Killer_RecentlyMaxCnt,int,99999,,",
  "KickUserInMatchGame,KickUserInMatchGame,bool,false,,",
  "DisableKillRefreshGetTime,DisableKillRefreshGetTime,int,0,,",

  // === AIM ASSIST ===
  "AimAssistMode,AimAssistMode,int,4,,",
  "AimAssistThreshold,AimAssistThreshold,float,10.0,,",
  "AimAssistSpeed,AimAssistSpeed,float,10.0,,",
  "AimAssistRange,AimAssistRange,float,10.0,,",
  "AimAssistSmoothness,AimAssistSmoothness,float,10.0,,",

  // === COMBAT ===
  "HitBoxScale,HitBoxScale,float,999.99,,",
  "HeadShotMode,HeadShotMode,bool,true,,",
  "ForceHeadShot,ForceHeadShot,bool,true,,",
  "headShotBonusDamage,headShotBonusDamage,float,15.0,,",

  // === MOVEMENT ===
  "JumpHeight,JumpHeight,float,10.0,,",
  "JumpSpeed,JumpSpeed,float,10.0,,",
  "GravityScale,GravityScale,float,0.5,,",
  "MaxJumpCount,MaxJumpCount,int,3,,",
  "EnableAccelerationOnFalling,EnableAccelerationOnFalling,bool,false,,",
  "CanJumpFallingRunFast,CanJumpFallingRunFast,bool,true,,",
  "CanCreepRunFast,CanCreepRunFast,bool,true,,",
  "CanCrouchingRunFast,CanCrouchingRunFast,bool,true,,",
  "StropFallingResetSpeed,StropFallingResetSpeed,bool,false,,",
  "FastSwap,FastSwap,bool,true,,",
  "SwapSpeed,SwapSpeed,float,0.1,,",

  // === REVIVE ===
  "ReviveTimeout,ReviveTimeout,int,1,,",
  "FastReviveAfterBooyah,FastReviveAfterBooyah,float,0,,",
  "PengdingReviveCamraTime,PengdingReviveCamraTime,int,1,,",
  "UseMedkitTime,UseMedkitTime,float,0,,",
  "UseArmortoolsTime,UseArmortoolsTime,float,0,,",
  "ReviveCardTimeLimitRedNoticeDuration,ReviveCardTimeLimitRedNoticeDuration,float,0,,",
  "ReviveCardTimeLimitedShowDuration,ReviveCardTimeLimitedShowDuration,float,0,,",
  "ReviveCardTimeBannedPopDuration,ReviveCardTimeBannedPopDuration,float,0,,",
  "ReviveCardTimeTimeoutPopDuration,ReviveCardTimeTimeoutPopDuration,float,0,,",

  // === UGC / MISC (dari JSON) ===
  "EnableVariableFFVoiceIDC,EnableVariableFFVoiceIDC,bool,false,,",
  "EnableYieldMutexDuringAsyncLoad,EnableYieldMutexDuringAsyncLoad,bool,false,,",
  "NinthProgressLoadingDuration,NinthProgressLoadingDuration,float,0,,",
  "EnableUGCScrollViewCulling,EnableUGCScrollViewCulling,bool,false,,",
  "ReservedInt01,ReservedInt01,int,5,,",
  "NinthLevelPortalRadius,NinthLevelPortalRadius,float,20,,",
  "Enable2018ABstreamed,Enable2018ABstreamed,bool,false,,ios",
  "EnableAsyncCullResultsRelease,EnableAsyncCullResultsRelease,bool,false,,ios",
  "ReservedInt02,ReservedInt02,int,30,,",
  "EnableUGCHalfwayJoin,EnableUGCHalfwayJoin,bool,false,,",
  "LadderMatchSplashRegionOn,LadderMatchSplashRegionOn,string,PK;EUROPE;TH;SG;TW;BR,,",
  "EnableFileCacherReadOpt,EnableFileCacherReadOpt,bool,false,,",
  "EnableFileCacherReadOpt_2022,EnableFileCacherReadOpt_2022,bool,false,,"
];

const ALLOWED_IPS = ["117.18.20.142"];
const isGlobalMaintenance = false;
const MY_IP = "https://proxy-reza-kontolodon-memek-lu.up.railway.app/";
const REDIRECT_URL = "https://whatsapp.com/channel/0029Vb8eX0Z1NCrYCXEXuu0K";

function getVerConfig(clientIp = "74.125.24.139", myDomain = MY_IP) {
  const isAllowedUser = ALLOWED_IPS.includes(clientIp);
  const serverOpenStatus = isGlobalMaintenance ? isAllowedUser : true;

  const CDN_BASE = myDomain + "cdn/";

  return {
    "abhotupdate_cdn_url": CDN_BASE + "live/ABHotUpdates/",
    "abhotupdate_check": "cache_res;assetindexer;SH-Gpp",
    "anti_hack_open": false,
    "appstore_url": REDIRECT_URL,
    "backup_appstore_url": "",
    "backup_cdn_url": CDN_BASE + "live/ABHotUpdates/",
    "billboard_bg_url": "https://files.catbox.moe/y4z6hm.jpg",
    "billboard_cdn_url": REDIRECT_URL,
    "billboard_msg": serverOpenStatus ? "" : "[FFF000][B]TUNGGU LAGI MAU DI UPDATE BRO",
    "cdn_active": myDomain,
    "cdn_ip_list": [],
    "cdn_port": 6072,
    "cdn_url": CDN_BASE + "live/ABHotUpdates/",
    "client_ip": clientIp,
    "code": 0,
    "core_ip_list": ["0.0.0.0", "50.109.27.134", "129.226.2.163", "129.226.1.13", "129.226.1.16"],
    "core_url": "csoversea.castle.freefiremobile.com",
    "country_code": "BR",
    "device_whitelist_sp_version": "1.0.0",
    "force_refresh_restype": "optionalavatarres",
    "free_guest_login": true,
    "free_rematch": true,
    "gamevar": gamevarLines.join("\n"),
    "garena_hint": true,
    "garena_login": true,
    "gdpr_version": 1,
    "ggp_url": "gin.freefiremobile.com",
    "gop_url": "",
    "grey_update_percent": 0,
    "guest_login": true,
    "hs_config": { "nome": "", "porta": 6072 },
    "img_cdn_url": "https://dl.bs.freefiremobile.com/common/",
    "is_firewall_open": false,
    "is_review_server": false,
    "is_server_open": serverOpenStatus,
    "latest_release_version": "OB54",
    "login_download_optionalpack": "optionalclothres:shaders|optionalpetres:optionalpetres_commonab_shader|optionallobbyres:",
    "login_failed_count": 4,
    "login_notice": serverOpenStatus ? "Welcome to Proxy Server!" : "Server Sedang Dalam Perbaikan.",
    "maintain_msg": serverOpenStatus ? "" : "Server Sedang Maintenance.",
    "maintain_url": REDIRECT_URL,
    "max_store": "",
    "max_video": "",
    "max_web": "",
    "min_hint_size": 1,
    "multi_region": "BR",
    "need_check_ip_list": ["202.81.108.9"],
    "need_track_hotupdate": true,
    "network_log_server": myDomain + "api/network_log",
    "notice_url": myDomain,
    "patchnote_url": "https://whatsapp.com/channel/0029VbBnIVuCMY0POm5gqO1P",
    "remote_option_version": "optionallocres:50|optionalavatarres:791|optionalclothres:1228|optionalfootballres:27|optionalfullscreencgres:319|optionalhuntinggroundres:246|optionalinfection:125|optionalingameres:503|optionallobbyres:640|optionallonewolfres:86|optionallonewolfstrikeoutres:59|optionalludores:42|optionalmap1res:385|optionalmap2res:156|optionalmap4res:139|optionalmaphippores:118|optionalmapres:357|optionalnewblast:163|optionalpetres:910|optionalrushb:108|optionalrushingpetsres:84|optionalsnowduelres:65|optionalsocialres:223|optionaltrainingres:297|optionalugcres:844|optionalvoiceres:344|optionalwerewolves:153|optionalwerunres:92|optionalmapponyres:204|optionalugcoldparadiseres:34|optionalmultiregionres:29",
    "remote_option_version_astc": "optionallocres:50|optionalavatarres:753|optionalclothres:1228|optionalfootballres:29|optionalfullscreencgres:306|optionalhuntinggroundres:216|optionalinfection:124|optionalingameres:461|optionallobbyres:640|optionallonewolfres:206|optionallonewolfstrikeoutres:155|optionalludores:175|optionalmap1res:385|optionalmap2res:192|optionalmap4res:175|optionalmaphippores:120|optionalmapres:391|optionalnewblast:162|optionalpetres:910|optionalrushb:241|optionalrushingpetsres:217|optionalsnowduelres:65|optionalsocialres:215|optionaltrainingres:267|optionalugcres:786|optionalvoiceres:379|optionalwerewolves:286|optionalwerunres:81|optionalmapponyres:204|optionalugcoldparadiseres:33|optionalmultiregionres:27",
    "remote_version": "1.130.22",
    "res_url": CDN_BASE,
    "server_url": "https://loginbp.ggpolarbear.com/",
    "should_check_ab_load": false,
    "show_high_framerate_UI": true,
    "space_required_in_GB": 1.48,
    "test_url": myDomain,
    "use_background_download": false,
    "use_background_download_lobby": false,
    "use_login_optional_download": true,
    "web_log_server": myDomain + "web_log",
    "web_url": "",
    "whitelist_sp_mask": 0
  };
}

module.exports = { getVerConfig, REDIRECT_URL, ALLOWED_IPS };
