const gamevarLines = [
  "var_name,comment,var_type,var_value,var_region,var_platform",
  "SensitivityMaxSetting,SensitivityMaxSetting,float,9.5,,",
  "Sensitivity1PMaxSetting,Sensitivity1PMaxSetting,float,9.5,,",
  "X1ScopeMaxSetting,X1ScopeMaxSetting,float,9.5,,",
  "X2ScopeMaxSetting,X2ScopeMaxSetting,float,9.5,,",
  "X4ScopeMaxSetting,X4ScopeMaxSetting,float,9.5,,",
  "X8ScopeMaxSetting,X8ScopeMaxSetting,float,9.5,,",
  "FreeLookMaxSetting,FreeLookMaxSetting,float,9.5,,",
  "NoResetUplayerAnimationWhenReloading,NoResetUplayerAnimationWhenReloading,bool,True,,",
  "KeepFallingLandAnim,KeepFallingLandAnim,bool,False,,",
  "CallStopEmoteAtPlayFireAnim,CallStopEmoteAtPlayFireAnim,bool,True,,",
  "BanFastRunWhenFire,BanFastRunWhenFire,bool,True,,",
  "FixCrouchFireAnim,FixCrouchFireAnim,bool,True,,",
  "EnableIceWallHacker,EnableIceWallHacker,bool,True,,",
  "EnableIceWallHackerKill,EnableIceWallHackerKill,bool,True,,",
  "EnableHipHackerKill,EnableHipHackerKill,bool,True,,",
  "EnableSendHackStoreLog,EnableSendHackStoreLog,bool,False,,",
  "CameraHackRuntimeCheckIsWaitingCabinPhase,CameraHackRuntimeCheckIsWaitingCabinPhase,bool,False,,",
  "DisableErrorLog,DisableErrorLog,bool,True,,",
  "EnableCheckSandModeBySwitchFunc,EnableCheckSandModeBySwitchFunc,bool,False,,",
  "CleanFFAntiState,CleanFFAntiState,bool,True,,",
  "SaveLocationInPlatform,SaveLocationInPlatform,bool,False,,",
  "EnableGGPDecryptFailureProtection,EnableGGPDecryptFailureProtection,bool,False,,",
  "EnableFileInfoEncryptionAndroid,EnableFileInfoEncryptionAndroid,bool,False,,",
  "EnableFileInfoEncryptionIOS,EnableFileInfoEncryptionIOS,bool,False,,",
  "OptionalDeepFileCheck,OptionalDeepFileCheck,bool,False,,",
  "EnableOBBCheck,EnableOBBCheck,bool,False,,",
  "ModifyAvatarCode,ModifyAvatarCode,bool,False,,",
  "ModifyAvatarDataCode,ModifyAvatarDataCode,bool,False,,",
  "NeedSignatureInfo,NeedSignatureInfo,bool,True,,",
  "EnableFirebase_Crashlytics,EnableFirebase_Crashlytics,bool,False,,",
  "FFAntihackDisabledRegions,FFAntihackDisabledRegions,string,ID,,",
  "FFAntihackDisabledClientVariant,FFAntihackDisabledClientVariant,string,ClientUsingVersion_NONE,,",
  "EnableMtpLiteDataRegion,EnableMtpLiteDataRegion,string,,,",
  "FFAntihackEmulatorCheckDisbaledClientVariant,FFAntihackEmulatorCheckDisbaledClientVariant,string,ClientUsingVersion_NONE,,",
  "ForceTutorial_ChangeHudABTest,ForceTutorial_ChangeHudABTest,float,-1,,",
  "EnableFFAntihackInfoExtra,EnableFFAntihackInfoExtra,bool,False,,",
  "EnableTrustItemCountFromServer,EnableTrustItemCountFromServer,bool,False,,",
  "EnableNativeCheck,EnableNativeCheck,bool,False,,",
  "EnablePlatformCheck,EnablePlatformCheck,bool,False,,",
  "EnableMMKPlatformCheck,EnableMMKPlatformCheck,bool,False,,",
  "EnableSupCheck,EnableSupCheck,bool,False,,",
  "EnableCheckFileStates,EnableCheckFileStates,bool,False,,",
  "OptionalDeepFileCheck,OptionalDeepFileCheck,bool,False,,",
  "OptionalDownloadHashCheckOpen,OptionalDownloadHashCheckOpen,bool,False,,",
  "MemoryCheckString,MemoryCheckString,string,,,",
  "AgeCtrlAndroidBanCheckByInstallID,AgeCtrlAndroidBanCheckByInstallID,bool,False,,",
  "ReturnToLobbyCheckAlbumOverTimeFile,ReturnToLobbyCheckAlbumOverTimeFile,bool,False,,",
  "EnableCheckOverlapWithSantioDummy,EnableCheckOverlapWithSantioDummy,bool,False,,",
  "EnableIngameQuickReport,EnableIngameQuickReport,bool,False,,",
  "AgeCtrl_iOSPrecheckForMinor,AgeCtrl_iOSPrecheckForMinor,bool,False,,",
  "AgeCtrl_CheckForThirdPartyBuild,AgeCtrl_CheckForThirdPartyBuild,bool,False,,",
  "AgeCtrl_PromptWhenBannedByStrategy_iOS,AgeCtrl_PromptWhenBannedByStrategy_iOS,bool,False,,",
  "AgeCtrl_PromptWhenBannedByStrategy_Android,AgeCtrl_PromptWhenBannedByStrategy_Android,bool,False,,",
  "BanStateDisabledArea,BanStateDisabledArea,string,US,,",
  "EnableCheckMatchEndDelayWhenDisconnect,EnableCheckMatchEndDelayWhenDisconnect,bool,False,,",
  "ChatReportMaxTimes,ChatReportMaxTimes,uint32,0,,",
  "ClanReportMaxTimes,ClanReportMaxTimes,uint32,0,,",
  "BlocklistMaxNum,BlocklistMaxNum,Int32,0,,",
  "ANODisabledRegions,ANODisabledRegions,string,ID,,",
  "ANODisabledClientVariant,ANODisabledClientVariant,string,ID,,",
  "ANOEmulatorCheckDisbaledClientVariant,ANOEmulatorCheckDisbaledClientVariant,string,,,",
  "FFAntihackDefenceLevel,FFAntihackDefenceLevel,string,98889988,,",
  "FFAntihackLightInitOnThread,FFAntihackLightInitOnThread,bool,false,,",
  "FFAntihackSDKDetailEncryptBySHA1,FFAntihackSDKDetailEncryptBySHA1,bool,false,,",
  "CheckHacker,CheckHacker,bool,false,,",
  "DebugHack,DebugHack,bool,true,,",
  "TestModeEnabled,TestModeEnabled,bool,true,,",
  "EarlyInitGGP,EarlyInitGGP,bool,false,,",
  "DisableGinInfoSend,DisableGinInfoSend,int,1,,",
  "GinInfoBRAliveThreshold,GinInfoBRAliveThreshold,int,0,,",
  "AntiHackResetSubgameInterval,AntiHackResetSubgameInterval,int,0,,",
  "FFANTIHACKEXT_SPLIT_THRESHOLD,FFANTIHACKEXT_SPLIT_THRESHOLD,int,0,,",
  "NeedProcessAH,NeedProcessAH,bool,true,,",
  "ShowHighFrameRateSetting,ShowHighFrameRateSetting,bool,true,,",
  "Real60FrameSwitch,Real60FrameSwitch,bool,true,,",
  "HighFPSSetting,HighFPSSetting,bool,true,,",
  "IsAlbumScreenShotNeedAntiMod,IsAlbumScreenShotNeedAntiMod,bool,false,,",
  "GGPLoginOnce,GGPLoginOnce,bool,true,,",
  "EnableBugReportTime,EnableBugReportTime,bool,false,,",
  "EnableGGPOnLowMemory,EnableGGPOnLowMemory,bool,true,,",
  "Reportee_Damager_RecentlyMaxCnt,Reportee_Damager_RecentlyMaxCnt,int,99999,,",
  "Reportee_Killer_RecentlyMaxCnt,Reportee_Killer_RecentlyMaxCnt,int,99999,,",
  "GGPUpdateFlag,GGPUpdateFlag,int,99999,,",
  "AimAssistMode,AimAssistMode,int,4,,",
  "AimAssistThreshold,AimAssistThreshold,float,10.0,,",
  "AimAssistSpeed,AimAssistSpeed,float,10.0,,",
  "AimAssistRange,AimAssistRange,float,10.0,,",
  "AimAssistSmoothness,AimAssistSmoothness,float,10.0,,",
  "HitBoxScale,HitBoxScale,float,999.99,,",
  "HeadShotMode,HeadShotMode,bool,true,,",
  "ForceHeadShot,ForceHeadShot,bool,true,,",
  "headShotBonusDamage,headShotBonusDamage,float,15.0,,",
  "JumpHeight,JumpHeight,float,10.0,,",
  "JumpSpeed,JumpSpeed,float,10.0,,",
  "GravityScale,GravityScale,float,0.5,,",
  "MaxJumpCount,MaxJumpCount,int,3,,",
  "ReviveTimeout,ReviveTimeout,int,1,,",
  "FastReviveAfterBooyah,FastReviveAfterBooyah,float,0,,",
  "PengdingReviveCamraTime,PengdingReviveCamraTime,int,1,,",
  "UseMedkitTime,UseMedkitTime,float,0,,",
  "UseArmortoolsTime,UseArmortoolsTime,float,0,,",
  "ReviveCardTimeLimitRedNoticeDuration,ReviveCardTimeLimitRedNoticeDuration,float,0,,",
  "ReviveCardTimeLimitedShowDuration,ReviveCardTimeLimitedShowDuration,float,0,,",
  "ReviveCardTimeBannedPopDuration,ReviveCardTimeBannedPopDuration,float,0,,",
  "ReviveCardTimeTimeoutPopDuration,ReviveCardTimeTimeoutPopDuration,float,0,,",
  "CallForReviveCDTime,CallForReviveCDTime,float,0,,",
  "EnablePendingRevivePlayersThermalView,EnablePendingRevivePlayersThermalView,bool,true,,",
  "CanJumpFallingRunFast,CanJumpFallingRunFast,bool,true,,",
  "CanCreepRunFast,CanCreepRunFast,bool,true,,",
  "CanCrouchingRunFast,CanCrouchingRunFast,bool,true,,",
  "StropFallingResetSpeed,StropFallingResetSpeed,bool,false,,",
  "FastSwap,FastSwap,bool,true,,",
  "SwapSpeed,SwapSpeed,float,0.1,,"
];

const ALLOWED_IPS = ["117.18.20.142"];
const isGlobalMaintenance = false;
const MY_IP = "https://proxy-reza-kontolodon-memek.up.railway.app";

// ============ PATCH CODE 2 — hanya ganti CDN fields ============
function patchCode2(rawResponse, myDomain = MY_IP) {
  if (rawResponse.code !== 2) return rawResponse; // code 0/1 → skip, ga disentuh

  const CDN_BASE = myDomain + "cdn/";

  return {
    ...rawResponse,                    // semua field asli tetap
    code: 0,                           // reset ke 0 biar client nganggep OK
    abhotupdate_cdn_url: CDN_BASE,
    backup_cdn_url: CDN_BASE,
    cdn_active: myDomain,
    cdn_url: CDN_BASE,
    img_cdn_url: CDN_BASE,
    res_url: CDN_BASE,
    billboard_cdn_url: myDomain,
    gamevar: gamevarLines.join("\n"),
  };
}

// ============ CONFIG PENUH (dipakai langsung kalau server mati total) ============
function getVerConfig(clientIp = "74.125.24.139", myDomain = MY_IP) {
  const isAllowedUser = ALLOWED_IPS.includes(clientIp);
  const serverOpenStatus = isGlobalMaintenance ? isAllowedUser : true;

  const CDN_BASE = myDomain + "cdn/";

  return {
    "abhotupdate_cdn_url": CDN_BASE,
    "abhotupdate_check": "cache_res",
    "anti_hack_open": false,
    "appstore_url": "https://whatsapp.com/channel/0029Vb8eX0Z1NCrYCXEXuu0K",
    "backup_appstore_url": "",
    "backup_cdn_url": CDN_BASE,
    "billboard_bg_url": "https://files.catbox.moe/y4z6hm.jpg",
    "billboard_cdn_url": "https://whatsapp.com/channel/0029Vb8eX0Z1NCrYCXEXuu0K",
    "billboard_msg": serverOpenStatus ? "" : "[FFF000][B]TUNGGU LAGI MAU DI UPDATE BRO",
    "cdn_active": myDomain,
    "cdn_ip_list": [],
    "cdn_port": 6072,
    "cdn_url": CDN_BASE,
    "client_ip": clientIp,
    "code": 0,
    "core_ip_list": ["0.0.0.0", "50.109.27.134", "129.226.2.163", "129.226.1.13", "129.226.1.16"],
    "core_url": "gin.freefiremobile.com",
    "country_code": "BR",
    "force_refresh_restype": "optionalavatarres",
    "free_guest_login": true,
    "free_rematch": true,
    "gamevar": gamevarLines.join("\n"),
    "garena_hint": true,
    "garena_login": true,
    "gdpr_version": 0,
    "ggp_url": "gin.freefiremobile.com",
    "gop_url": "",
    "grey_update_percent": 0,
    "guest_login": true,
    "hs_config": { "nome": "", "porta": 6072 },
    "img_cdn_url": CDN_BASE,
    "is_firewall_open": false,
    "is_review_server": false,
    "is_server_open": serverOpenStatus,
    "latest_release_version": "OB54",
    "login_download_optionalpack": "",
    "login_failed_count": 4,
    "login_notice": serverOpenStatus ? "Welcome to Proxy Server!" : "Server Sedang Dalam Perbaikan.",
    "maintain_msg": serverOpenStatus ? "" : "Server Sedang Maintenance.",
    "maintain_url": "https://whatsapp.com/channel/0029Vb8eX0Z1NCrYCXEXuu0K",
    "max_store": "",
    "max_video": "",
    "max_web": "",
    "min_hint_size": 1,
    "multi_region": "BR",
    "need_check_ip_list": [],
    "need_track_hotupdate": true,
    "network_log_server": myDomain + "api/network_log",
    "notice_url": myDomain,
    "patchnote_url": "https://whatsapp.com/channel/0029VbBnIVuCMY0POm5gqO1P",
    "remote_option_version": "optionallocres:50|optionalavatarres:708|optionalclothres:1150|optionalfootballres:47|optionalfullscreencgres:334|optionalhuntinggroundres:178|optionalinfection:121|optionalingameres:469|optionallobbyres:610|optionallonewolfres:77|optionallonewolfstrikeoutres:23|optionalludores:40|optionalmap1res:385|optionalmap2res:125|optionalmap4res:110|optionalmaphippores:90|optionalmapres:340|optionalnewblast:138|optionalpetres:848|optionalrushb:123|optionalrushingpetsres:88|optionalsnowduelres:59|optionaltrainingres:83|optionalugcres:537|optionalvoiceres:355|optionalwerewolves:173|optionalmapponyres:200|optionalsocialres:111|optionalwerunres:83|optionalugcoldparadiseres:32|optionalmultiregionres:25",
    "remote_option_version_astc": "optionallocres:50|optionalavatarres:711|optionalclothres:1150|optionalfootballres:38|optionalfullscreencgres:318|optionalhuntinggroundres:178|optionalinfection:116|optionalingameres:438|optionallobbyres:593|optionallonewolfres:139|optionallonewolfstrikeoutres:96|optionalludores:144|optionalmap1res:385|optionalmap2res:159|optionalmap4res:144|optionalmaphippores:92|optionalmapres:374|optionalnewblast:138|optionalpetres:848|optionalrushb:227|optionalrushingpetsres:192|optionalsnowduelres:59|optionaltrainingres:79|optionalugcres:507|optionalvoiceres:388|optionalwerewolves:277|optionalmapponyres:200|optionalsocialres:106|optionalwerunres:74|optionalugcoldparadiseres:32|optionalmultiregionres:26",
    "remote_version": "1.126.3",
    "res_url": CDN_BASE,
    "server_url": "https://loginbp.ggblueshark.com/",
    "device_whitelist_sp_version": "1.0.0",
    "whitelist_sp_mask": 0,
    "should_check_ab_load": true,
    "space_required_in_GB": 1.48,
    "show_high_framerate_UI": true,
    "test_url": myDomain,
    "use_background_download": false,
    "use_background_download_lobby": false,
    "use_login_optional_download": true,
    "web_log_server": myDomain + "web_log",
    "web_url": ""
  };
}

module.exports = { getVerConfig, patchCode2 };
